export enum ServiceType {
  ENTERTAINMENT = 'ENTERTAINMENT',
  MUSIC = 'MUSIC',
  GAMES = 'GAMES',
  EDUCATION = 'EDUCATION',
  FINANCIAL = 'FINANCIAL',
  HEALTH = 'HEALTH',
  PRODUCTIVITY = 'PRODUCTIVITY',
  BEAUTY = 'BEAUTY',
  PET = 'PET',
  OTHERS = 'OTHERS',
}
